### ISSUE TITLE
Default to zip code lat/long on ambassador signup when no address match is found by census.gov API

### ISSUE THREAD

**Issue by shauminn-colab** [colab-coop/HelloVoter#43]
As an ambassador, I want to sign up and have my location set based on zip code if I enter an address that isn't in the Census database.

- When an ambassador signs up, their address is currently checked against census.gov API.  The update here is if no match is found in census database, then we should default to using ambassador's zip code to set their latitude and longitude
- Convert this zip/latlong dataset into a JSON object (**Zip Code/LatLong Reference Dataset**: https://public.opendatasoft.com/explore/dataset/us-zip-code-latitude-and-longitude/table/)
- Reference the JSON object when fallback to zip code is needed for lat/long lookup

**Comment by azrap** [comment]
PR for this issue: https://github.com/colab-coop/HelloVoter/pull/50

**Comment by shauminn-colab** [comment]
Test results - overall a PASS 👏  Just a few edgier cases with fake zip codes that I can create a new ticket for to address. Overall excellent! 
-- 

Real address NOT in census database (7311 S Placita de Cordorniz Tucson, AZ) + real zip code (85747)
RESULT: PASS - latlong was set to a location within about 2 miles of the address (centroid of zip code)

Real address NOT in census database (7311 S Placita de Cordorniz Tucson, AZ) + fake zip code (00000):
RESULT:  FAIL - Address given was in Tucson AZ. Latlong was set to a spot in Indiana ( 39.792993 / -86.285750 )

Real address in census db (1604 Alderman Dr Greensboro, NC) + fake zip code (00000)
RESULT: PASS - Because address is recognized by census, fake zip code is not an issue. Correct latlong set.

Real address in census db (1604 Alderman Dr Greensboro, NC) + real zip code (27408)
RESULT: PASS - happy path, correct latlong set

Fake address  (12345 Happyfun Lane Sillyville, FL) + fake zip code (00000)
RESULT: FAIL - Same latlong in Indiana ( 39.792993 / -86.285750 ) was set

**Comment by cooperka** [comment]
Casual inquiry @shauminn-colab: I noticed there are about 8 different places where user addresses get geoCoded, but only one of them (ambassador signup, as described in the issue title) falls back to using zipcode if the address isn't in the census data.

Instead of falling back in just that one place, we could easily fall back inside the `geoCode` method itself and then everywhere will automatically get this benefit. Is that desirable? It would be a small change but may require more testing.

**Comment by shauminn-colab** [comment]
Hey @cooperka - thanks for inquiring :) 

We only do geocoding on the fly for the ambassador address at signup based on census API. When address isn't found we fall back to zip code and use that to roughly place their lat/long.  The triplers' lat/long is part of the ingest script. We don't geocode those in the system.
