### ISSUE TITLE
Tripler month/day of birth entered by ambassador should be stored in backend

### ISSUE THREAD

**Issue by shauminn-colab** [colab-coop/HelloVoter#86]
When an ambassador enters the month/day of the tripler they are contacting to start the confirmation process, we should store that month/day entered for the tripler

No need for server validation, the ambassador can enter the month/day string in any format

**Comment by azrap** [comment]
@shauminn-colab dob has been added to triplers.csv! pending testing after the DB change from Lee. I am not sure what we mean by "should be passed to Triplers.json" here. Please let me know and I'm happy to add that

**Comment by shauminn-colab** [comment]
Woo woo! So check out line 70 here: https://github.com/colab-coop/HelloVoter/blob/ambassador-stage2/server/app/services/export.js  we recently added ability to export tripler data in json format rather than just CSV format.  Let me know if that clarifies :)

**Comment by azrap** [comment]
ahh I hadn't pulled in the latest changes SMH. Thanks!
